jaffle_shop:
  outputs:
    dev:
      type: postgres
      host: postgres
      user: admin
      password: test123
      port: 5432
      dbname: postgresdb
      schema: jaffle_shop
      threads: 1
  target: dev