apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-db
spec:
  serviceName: postgresql-db-service
  selector:
    matchLabels:
      app: postgresql-db
  replicas: 2
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      containers:
      - name: postgresql-db
        image: postgres:13-bullseye
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        # Resource Limits
        resources:
          requests:
            memory: "265Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        # Data Volume
        volumeMounts:
        - name: postgresql-db-disk
          mountPath: /data
      # Point to ConfigMap
        envFrom:
        - configMapRef:
            name: postgres-db-config
# Volume Claim
  volumeClaimTemplates:
  - metadata:
      name: postgresql-db-disk
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 25Gi